# Generated by Django 3.1.7 on 2021-04-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Souq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('img', models.TextField()),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('lastprice', models.CharField(blank=True, max_length=50, null=True)),
                ('souqId', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'souq',
            },
        ),
    ]
