# Generated by Django 3.1.7 on 2021-04-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souq',
            name='sku',
        ),
    ]
