# Generated by Django 3.1.7 on 2021-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0002_remove_souq_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souq',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='souq',
            name='souqId',
            field=models.TextField(),
        ),
    ]
