# Generated by Django 3.1.7 on 2021-04-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('souq', '0003_auto_20210403_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='souq',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='souq', to='products.category', verbose_name='category'),
        ),
    ]
