# Generated by Django 3.1.7 on 2021-04-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souq', '0004_souq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='souq',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
