# Generated by Django 3.1.7 on 2021-04-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0003_remove_jumia_jumiaid'),
        ('noon', '0001_initial'),
        ('souq', '0006_auto_20210404_1340'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumia', to='jumia.jumia', verbose_name='jumia')),
                ('noon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noon', to='noon.noon', verbose_name='noon')),
                ('souq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souq', to='souq.souq', verbose_name='souq')),
            ],
        ),
    ]
