# Generated by Django 3.1.7 on 2021-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('souqid', models.CharField(max_length=200)),
                ('lastPrice', models.CharField(max_length=200)),
            ],
        ),
    ]
