# Generated by Django 3.1.5 on 2021-02-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210210_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.IntegerField(db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='img',
            name='id',
            field=models.IntegerField(db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jumia',
            name='id',
            field=models.IntegerField(db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notify',
            name='id',
            field=models.IntegerField(db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price_history',
            name='productID',
            field=models.IntegerField(db_column='productID', default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='souq',
            name='id',
            field=models.IntegerField(db_column='id', default='', primary_key=True, serialize=False),
        ),
    ]
