# Generated by Django 3.1.5 on 2021-02-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210210_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.IntegerField(blank=True, db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='img',
            name='id',
            field=models.IntegerField(blank=True, db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='img',
            name='productID',
            field=models.IntegerField(blank=True, db_column='productID', null=True),
        ),
        migrations.AlterField(
            model_name='jumia',
            name='JumiaID',
            field=models.IntegerField(blank=True, db_column='JumiaID', null=True),
        ),
        migrations.AlterField(
            model_name='jumia',
            name='id',
            field=models.IntegerField(blank=True, db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jumia',
            name='productID',
            field=models.IntegerField(blank=True, db_column='productID', null=True),
        ),
        migrations.AlterField(
            model_name='noon',
            name='NoonID',
            field=models.IntegerField(blank=True, db_column='NoonID', null=True),
        ),
        migrations.AlterField(
            model_name='noon',
            name='id',
            field=models.IntegerField(blank=True, db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noon',
            name='productID',
            field=models.IntegerField(blank=True, db_column='productID', null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='customerID',
            field=models.IntegerField(blank=True, db_column='customerID', null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='id',
            field=models.IntegerField(blank=True, db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notify',
            name='productID',
            field=models.IntegerField(blank=True, db_column='productID', null=True),
        ),
        migrations.AlterField(
            model_name='price_history',
            name='productID',
            field=models.IntegerField(blank=True, db_column='productID', default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SouqID',
            field=models.IntegerField(blank=True, db_column='SouqID', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(blank=True, db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='souq',
            name='SouqID',
            field=models.IntegerField(blank=True, db_column='SouqID', null=True),
        ),
        migrations.AlterField(
            model_name='souq',
            name='id',
            field=models.IntegerField(blank=True, db_column='id', default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='souq',
            name='productID',
            field=models.IntegerField(blank=True, db_column='productID', null=True),
        ),
    ]
