# Generated by Django 3.1.5 on 2021-02-10 23:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210211_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumia',
            name='id',
            field=models.AutoField(db_column='id', default=blog.models.Jumia.increment_id, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
