# Generated by Django 3.1.5 on 2021-02-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210211_0102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='jumia',
            name='CATEGORIES',
        ),
        migrations.RemoveField(
            model_name='jumia',
            name='status',
        ),
        migrations.RemoveField(
            model_name='noon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='souq',
            name='category',
        ),
        migrations.AlterField(
            model_name='jumia',
            name='JumiaID',
            field=models.IntegerField(db_column='JumiaID', null=True),
        ),
        migrations.AlterField(
            model_name='jumia',
            name='productID',
            field=models.IntegerField(db_column='productID', null=True),
        ),
    ]
