# Generated by Django 3.1.7 on 2021-04-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0002_auto_20210404_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumia',
            name='jumiaId',
        ),
    ]
