# Generated by Django 3.1.5 on 2021-02-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souq',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('ean', models.CharField(db_column='ean', max_length=50)),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('manufacture', models.CharField(db_column='manufacture', max_length=50)),
                ('category', models.IntegerField(db_column='category')),
                ('active', models.BooleanField(db_column='active')),
                ('lastPrice', models.CharField(db_column='lastPrice', max_length=50)),
                ('mainImg', models.TextField(db_column='mainImg')),
                ('productID', models.IntegerField(db_column='productID')),
                ('fullDescription', models.TextField(db_column='fullDescription')),
                ('rate', models.FloatField(db_column='rate')),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
