# Generated by Django 3.1.5 on 2021-02-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0002_souq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('productID', models.IntegerField(db_column='productID')),
                ('imgPath', models.CharField(db_column='imgPath', max_length=300)),
            ],
            options={
                'verbose_name': 'Img',
            },
        ),
        migrations.CreateModel(
            name='Jumia',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('sku', models.CharField(db_column='sku', max_length=50)),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('manufacture', models.CharField(db_column='manufacture', max_length=50)),
                ('category', models.IntegerField(db_column='category')),
                ('active', models.BooleanField(db_column='active')),
                ('lastPrice', models.CharField(db_column='lastPrice', max_length=50)),
                ('mainImg', models.TextField(db_column='mainImg')),
                ('productID', models.IntegerField(db_column='productID')),
                ('fullDescription', models.TextField(db_column='fullDescription')),
                ('JumiaID', models.IntegerField(db_column='JumiaID')),
                ('rate', models.FloatField(db_column='rate')),
            ],
            options={
                'verbose_name_plural': 'Jumias',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.IntegerField(db_column='name')),
                ('url', models.CharField(db_column='url', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'MainCategories',
            },
        ),
        migrations.CreateModel(
            name='Noon',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('sku', models.CharField(db_column='sku', max_length=50)),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('manufacture', models.CharField(db_column='manufacture', max_length=50)),
                ('category', models.IntegerField(db_column='category')),
                ('active', models.BooleanField(db_column='active')),
                ('lastPrice', models.CharField(db_column='lastPrice', max_length=50)),
                ('mainImg', models.TextField(db_column='mainImg')),
                ('productID', models.IntegerField(db_column='productID')),
                ('fullDescription', models.TextField(db_column='fullDescription')),
                ('NoonID', models.IntegerField(db_column='NoonID')),
                ('rate', models.FloatField(db_column='rate')),
            ],
            options={
                'verbose_name_plural': 'Noons',
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('customerID', models.IntegerField(db_column='customerID')),
                ('productID', models.IntegerField(db_column='productID')),
                ('ImPrice', models.CharField(db_column='ImPrice', max_length=100)),
                ('ended', models.BooleanField(db_column='ended')),
            ],
            options={
                'verbose_name_plural': 'Notifies',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField(db_column='productID')),
                ('dateOFchange', models.DateField(db_column='dateOFchange')),
                ('price', models.CharField(db_column='price', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'PriceHistories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('ean', models.CharField(db_column='ean', max_length=50)),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('manufacture', models.CharField(db_column='manufacture', max_length=50)),
                ('category', models.IntegerField(db_column='category')),
                ('active', models.BooleanField(db_column='active')),
                ('lastPrice', models.CharField(db_column='lastPrice', max_length=50)),
                ('mainImg', models.TextField(db_column='mainImg')),
                ('fullDescription', models.TextField(db_column='fullDescription')),
                ('SouqID', models.IntegerField(db_column='SouqID')),
                ('avgRating', models.FloatField(db_column='avgRating')),
                ('img', models.IntegerField(db_column='img')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='souq',
            options={'verbose_name_plural': 'Souqs'},
        ),
    ]
